project:
  type: website

website:
  title: "Faulkner and Punctuation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: text_processing_supplement_outliers.qmd
        text: Outliers
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

